Debug testing
Signed-off-by: Charlie Truong <chtruong@nvidia.com>

diff --git a/.github/workflows/cicd-main.yml b/.github/workflows/cicd-main.yml
--- a/.github/workflows/cicd-main.yml
+++ b/.github/workflows/cicd-main.yml
@@ -40,101 +40,101 @@ jobs:
     secrets:
       NVIDIA_MANAGEMENT_ORG_PAT: ${{ secrets.NVIDIA_MANAGEMENT_ORG_PAT }}
 
-  linting:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-      - name: Setup Python
-        uses: actions/setup-python@v5
-        with:
-          python-version: "3.10"
-      - name: Set up UV
-        uses: astral-sh/setup-uv@v1
-        with:
-          version: 0.8.22
-      - name: Install ruff
-        env:
-          UV_PROJECT_ENVIRONMENT: ./venv
-        run: |
-          uv venv ${UV_PROJECT_ENVIRONMENT} --system-site-packages
-          source ./venv/bin/activate
+  # linting:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
+  #     - name: Setup Python
+  #       uses: actions/setup-python@v5
+  #       with:
+  #         python-version: "3.10"
+  #     - name: Set up UV
+  #       uses: astral-sh/setup-uv@v1
+  #       with:
+  #         version: 0.8.22
+  #     - name: Install ruff
+  #       env:
+  #         UV_PROJECT_ENVIRONMENT: ./venv
+  #       run: |
+  #         uv venv ${UV_PROJECT_ENVIRONMENT} --system-site-packages
+  #         source ./venv/bin/activate
 
-          export PATH="./bin/:$PATH"
+  #         export PATH="./bin/:$PATH"
 
-          uv sync --link-mode copy --locked --group linting
+  #         uv sync --link-mode copy --locked --group linting
 
-      - name: Run ruff
-        run: |
-          source ./venv/bin/activate
-          uv run --active ruff --version
-          uv run --active ruff check --verbose .
-          uv run --active ruff format --check --verbose .
+  #     - name: Run ruff
+  #       run: |
+  #         source ./venv/bin/activate
+  #         uv run --active ruff --version
+  #         uv run --active ruff check --verbose .
+  #         uv run --active ruff format --check --verbose .
 
-  import_linting:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-      - name: Setup Python
-        uses: actions/setup-python@v5
-        with:
-          python-version: "3.10"
-      - name: Set up UV
-        uses: astral-sh/setup-uv@v1
-        with:
-          version: 0.8.22
-      - name: Install ruff
-        env:
-          UV_PROJECT_ENVIRONMENT: ./venv
-        run: |
-          uv venv ${UV_PROJECT_ENVIRONMENT} --system-site-packages
-          source ./venv/bin/activate
+  # import_linting:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
+  #     - name: Setup Python
+  #       uses: actions/setup-python@v5
+  #       with:
+  #         python-version: "3.10"
+  #     - name: Set up UV
+  #       uses: astral-sh/setup-uv@v1
+  #       with:
+  #         version: 0.8.22
+  #     - name: Install ruff
+  #       env:
+  #         UV_PROJECT_ENVIRONMENT: ./venv
+  #       run: |
+  #         uv venv ${UV_PROJECT_ENVIRONMENT} --system-site-packages
+  #         source ./venv/bin/activate
 
-          export PATH="./bin/:$PATH"
+  #         export PATH="./bin/:$PATH"
 
-          uv sync --link-mode copy --locked --group linting
+  #         uv sync --link-mode copy --locked --group linting
 
-      - name: Run import-linter
-        run: |
-          source ./venv/bin/activate
-          uv run lint-imports --debug --verbose --no-cache
+  #     - name: Run import-linter
+  #       run: |
+  #         source ./venv/bin/activate
+  #         uv run lint-imports --debug --verbose --no-cache
 
-  Nemo_Linting_Test:
-    needs: [linting, import_linting]
-    runs-on: ubuntu-latest
-    if: always()
-    steps:
-      - name: Main
-        env:
-          LINTING_RESULT: ${{ toJson(needs.linting) }}
-          IMPORT_LINTING_RESULT: ${{ toJson(needs.import_linting) }}
-        run: |
-          LINTING=$(echo "$LINTING_RESULT" | jq -r '.result')
-          IMPORT_LINTING=$(echo "$IMPORT_LINTING_RESULT" | jq -r '.result')
+  # Nemo_Linting_Test:
+  #   needs: [linting, import_linting]
+  #   runs-on: ubuntu-latest
+  #   if: always()
+  #   steps:
+  #     - name: Main
+  #       env:
+  #         LINTING_RESULT: ${{ toJson(needs.linting) }}
+  #         IMPORT_LINTING_RESULT: ${{ toJson(needs.import_linting) }}
+  #       run: |
+  #         LINTING=$(echo "$LINTING_RESULT" | jq -r '.result')
+  #         IMPORT_LINTING=$(echo "$IMPORT_LINTING_RESULT" | jq -r '.result')
 
-          if [[ "$LINTING" == "success" ]] && [[ "$IMPORT_LINTING" == "success" ]]; then
-            echo "All linting checks passed."
-            exit 0
-          else
-            echo "Some linting checks failed:"
-            echo "  - linting: $LINTING"
-            echo "  - import_linting: $IMPORT_LINTING"
-            exit 1
-          fi
+  #         if [[ "$LINTING" == "success" ]] && [[ "$IMPORT_LINTING" == "success" ]]; then
+  #           echo "All linting checks passed."
+  #           exit 0
+  #         else
+  #           echo "Some linting checks failed:"
+  #           echo "  - linting: $LINTING"
+  #           echo "  - import_linting: $IMPORT_LINTING"
+  #           exit 1
+  #         fi
 
-  cicd-wait-in-queue:
-    needs: [pre-flight]
-    runs-on: ubuntu-latest
-    environment: test
-    if: |
-      !(needs.pre-flight.outputs.is_ci_workload == 'true'
-      || needs.pre-flight.outputs.is_deployment_workflow == 'true'
-      || needs.pre-flight.outputs.docs_only == 'true')
-    steps:
-      - name: Running CI tests
-        run: |
-          echo "Running CI tests"
+  # cicd-wait-in-queue:
+  #   needs: [pre-flight]
+  #   runs-on: ubuntu-latest
+  #   environment: test
+  #   if: |
+  #     !(needs.pre-flight.outputs.is_ci_workload == 'true'
+  #     || needs.pre-flight.outputs.is_deployment_workflow == 'true'
+  #     || needs.pre-flight.outputs.docs_only == 'true')
+  #   steps:
+  #     - name: Running CI tests
+  #       run: |
+  #         echo "Running CI tests"
 
   cicd-unit-tests:
     strategy:
@@ -142,14 +142,14 @@ jobs:
       max-parallel: 5
       matrix:
         include:
-          - test-name: L0_Unit_Tests_CPU
-            runner: linux-amd64-cpu16
-            cpu-only: true
+          # - test-name: L0_Unit_Tests_CPU
+          #   runner: linux-amd64-cpu16
+          #   cpu-only: true
           - test-name: L0_Unit_Tests_GPU
             runner: ${{ needs.pre-flight.outputs.runner_prefix }}-gpu-x2
             cpu-only: false
             timeout: 30
-    needs: [pre-flight, cicd-wait-in-queue]
+    needs: [pre-flight]
     runs-on: ${{ matrix.runner }}
     name: ${{ matrix.test-name }}
     environment: nemo-ci
@@ -176,76 +176,76 @@ jobs:
           PAT: ${{ secrets.PAT }}
           test-data-path: ${{ needs.pre-flight.outputs.test_data_path }}
 
-  cicd-e2e-tests:
-    strategy:
-      fail-fast: false
-      max-parallel: 10
-      matrix:
-        include:
-          - test-name: L2_Pretrain_and_KD
-            test-folder: llm_pretrain_and_kd
-            runner: ${{ needs.pre-flight.outputs.runner_prefix }}-gpu-x2
-            timeout: 20
-          - test-name: L2_HF_DCP
-            test-folder: hf_dcp
-            runner: ${{ needs.pre-flight.outputs.runner_prefix }}-gpu-x2
-            timeout: 40
-          - test-name: L2_HF_PEFT
-            test-folder: hf_peft
-            runner: ${{ needs.pre-flight.outputs.runner_prefix }}-gpu-x2
-            timeout: 30
-          - test-name: L2_HF_Transformer
-            test-folder: hf_transformer
-            runner: ${{ needs.pre-flight.outputs.runner_prefix }}-gpu-x2
-            timeout: 20
-          - test-name: L2_HF_Transformer_Finetune
-            test-folder: hf_transformer_finetune
-            runner: ${{ needs.pre-flight.outputs.runner_prefix }}-gpu-x2
-            timeout: 40
-          - test-name: L2_HF_Transformer_LLM
-            test-folder: hf_transformer_llm
-            runner: ${{ needs.pre-flight.outputs.runner_prefix }}-gpu-x2
-            timeout: 40
-          - test-name: L2_HF_Transformer_VLM
-            test-folder: hf_transformer_vlm
-            runner: ${{ needs.pre-flight.outputs.runner_prefix }}-gpu-x2
-            timeout: 60
-          - test-name: L2_Datasets
-            test-folder: data
-            runner: ${{ needs.pre-flight.outputs.runner_prefix }}-gpu-x2
-            timeout: 20
-    needs: [cicd-unit-tests, pre-flight]
-    runs-on: ${{ matrix.runner }}
-    name: ${{ matrix.test-name }}
-    environment: nemo-ci
-    if: |
-      (
-        success()
-        || needs.pre-flight.outputs.is_ci_workload == 'true'
-        || needs.pre-flight.outputs.force_run_all == 'true'
-      )
-      && !cancelled()
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-      - name: main
-        uses: ./.github/actions/test-template
-        with:
-          test-folder: ${{ matrix.test-folder }}
-          timeout: ${{ matrix.timeout }}
-          is_unit_test: "false"
-          has-azure-credentials: "true"
-          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
-          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
-          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
-          PAT: ${{ secrets.PAT }}
-          test-data-path: ${{ needs.pre-flight.outputs.test_data_path }}
+  # cicd-e2e-tests:
+  #   strategy:
+  #     fail-fast: false
+  #     max-parallel: 10
+  #     matrix:
+  #       include:
+  #         - test-name: L2_Pretrain_and_KD
+  #           test-folder: llm_pretrain_and_kd
+  #           runner: ${{ needs.pre-flight.outputs.runner_prefix }}-gpu-x2
+  #           timeout: 20
+  #         - test-name: L2_HF_DCP
+  #           test-folder: hf_dcp
+  #           runner: ${{ needs.pre-flight.outputs.runner_prefix }}-gpu-x2
+  #           timeout: 40
+  #         - test-name: L2_HF_PEFT
+  #           test-folder: hf_peft
+  #           runner: ${{ needs.pre-flight.outputs.runner_prefix }}-gpu-x2
+  #           timeout: 30
+  #         - test-name: L2_HF_Transformer
+  #           test-folder: hf_transformer
+  #           runner: ${{ needs.pre-flight.outputs.runner_prefix }}-gpu-x2
+  #           timeout: 20
+  #         - test-name: L2_HF_Transformer_Finetune
+  #           test-folder: hf_transformer_finetune
+  #           runner: ${{ needs.pre-flight.outputs.runner_prefix }}-gpu-x2
+  #           timeout: 40
+  #         - test-name: L2_HF_Transformer_LLM
+  #           test-folder: hf_transformer_llm
+  #           runner: ${{ needs.pre-flight.outputs.runner_prefix }}-gpu-x2
+  #           timeout: 40
+  #         - test-name: L2_HF_Transformer_VLM
+  #           test-folder: hf_transformer_vlm
+  #           runner: ${{ needs.pre-flight.outputs.runner_prefix }}-gpu-x2
+  #           timeout: 60
+  #         - test-name: L2_Datasets
+  #           test-folder: data
+  #           runner: ${{ needs.pre-flight.outputs.runner_prefix }}-gpu-x2
+  #           timeout: 20
+  #   needs: [cicd-unit-tests, pre-flight]
+  #   runs-on: ${{ matrix.runner }}
+  #   name: ${{ matrix.test-name }}
+  #   environment: nemo-ci
+  #   if: |
+  #     (
+  #       success()
+  #       || needs.pre-flight.outputs.is_ci_workload == 'true'
+  #       || needs.pre-flight.outputs.force_run_all == 'true'
+  #     )
+  #     && !cancelled()
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
+  #     - name: main
+  #       uses: ./.github/actions/test-template
+  #       with:
+  #         test-folder: ${{ matrix.test-folder }}
+  #         timeout: ${{ matrix.timeout }}
+  #         is_unit_test: "false"
+  #         has-azure-credentials: "true"
+  #         azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
+  #         azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
+  #         azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+  #         PAT: ${{ secrets.PAT }}
+  #         test-data-path: ${{ needs.pre-flight.outputs.test_data_path }}
 
   Nemo_CICD_Test:
     needs:
       - pre-flight
       - cicd-unit-tests
-      - cicd-e2e-tests
+      # - cicd-e2e-tests
     if: |
       (
         needs.pre-flight.outputs.docs_only == 'true'
@@ -280,77 +280,77 @@ jobs:
               exit 1
           fi
 
-  Coverage_Fake:
-    runs-on: ubuntu-latest
-    needs: [Nemo_CICD_Test, pre-flight]
-    if: |
-      (
-        needs.pre-flight.outputs.docs_only == 'true'
-        || needs.pre-flight.outputs.is_deployment_workflow == 'true'
-      )
-      && needs.pre-flight.outputs.is_ci_workload == 'false'
-      && !cancelled()
-    environment: nemo-ci
-    steps:
-      - name: Generate fake coverage report
-        uses: actions/github-script@v6
-        with:
-          github-token: ${{ secrets.PAT }}
-          script: |
-            await github.rest.repos.createCommitStatus({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              sha: context.sha,
-              state: 'success',
-              description: 'No code changes - coverage check skipped',
-              context: 'codecov/patch'
-            });
+  # Coverage_Fake:
+  #   runs-on: ubuntu-latest
+  #   needs: [Nemo_CICD_Test, pre-flight]
+  #   if: |
+  #     (
+  #       needs.pre-flight.outputs.docs_only == 'true'
+  #       || needs.pre-flight.outputs.is_deployment_workflow == 'true'
+  #     )
+  #     && needs.pre-flight.outputs.is_ci_workload == 'false'
+  #     && !cancelled()
+  #   environment: nemo-ci
+  #   steps:
+  #     - name: Generate fake coverage report
+  #       uses: actions/github-script@v6
+  #       with:
+  #         github-token: ${{ secrets.PAT }}
+  #         script: |
+  #           await github.rest.repos.createCommitStatus({
+  #             owner: context.repo.owner,
+  #             repo: context.repo.repo,
+  #             sha: context.sha,
+  #             state: 'success',
+  #             description: 'No code changes - coverage check skipped',
+  #             context: 'codecov/patch'
+  #           });
 
-  Coverage:
-    runs-on: ubuntu-latest
-    needs: [pre-flight, Nemo_CICD_Test]
-    if: |
-      (
-        (needs.pre-flight.outputs.is_ci_workload == 'true' && !failure())
-        || success()
-      )
-      && !cancelled()
-    strategy:
-      matrix:
-        flag: [unit-test, e2e]
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
+  # Coverage:
+  #   runs-on: ubuntu-latest
+  #   needs: [pre-flight, Nemo_CICD_Test]
+  #   if: |
+  #     (
+  #       (needs.pre-flight.outputs.is_ci_workload == 'true' && !failure())
+  #       || success()
+  #     )
+  #     && !cancelled()
+  #   strategy:
+  #     matrix:
+  #       flag: [unit-test, e2e]
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
 
-      - name: Download coverage reports of current branch
-        uses: actions/download-artifact@v4
-        with:
-          pattern: coverage-${{ matrix.flag }}-*
+  #     - name: Download coverage reports of current branch
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         pattern: coverage-${{ matrix.flag }}-*
 
-      - name: Get total coverage of current branch
-        shell: bash -x -e -u -o pipefail {0}
-        if: always()
-        run: |
-          pip install coverage[toml]
+  #     - name: Get total coverage of current branch
+  #       shell: bash -x -e -u -o pipefail {0}
+  #       if: always()
+  #       run: |
+  #         pip install coverage[toml]
 
-          ls -al .
-          ls -al coverage-*/
-          coverage combine --keep $(ls coverage-*/.coverage)
-          coverage report -i
-          rm -rf coverage-*
-          ls -al
+  #         ls -al .
+  #         ls -al coverage-*/
+  #         coverage combine --keep $(ls coverage-*/.coverage)
+  #         coverage report -i
+  #         rm -rf coverage-*
+  #         ls -al
 
-      - name: Upload coverage reports to Codecov
-        uses: codecov/codecov-action@v5
-        with:
-          token: ${{ secrets.CODECOV_TOKEN }}
-          verbose: true
-          flags: ${{ matrix.flag }}
+  #     - name: Upload coverage reports to Codecov
+  #       uses: codecov/codecov-action@v5
+  #       with:
+  #         token: ${{ secrets.CODECOV_TOKEN }}
+  #         verbose: true
+  #         flags: ${{ matrix.flag }}
 
-      - name: Upload artifacts
-        uses: actions/upload-artifact@v4
-        with:
-          name: coverage-${{ matrix.flag }}-aggregated
-          path: |
-            .coverage
-          include-hidden-files: true
+  #     - name: Upload artifacts
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: coverage-${{ matrix.flag }}-aggregated
+  #         path: |
+  #           .coverage
+  #         include-hidden-files: true
